### ISSUE TITLE
[No Data] Example from the README file not working (Alparray)

### ISSUE THREAD

**Issue by javiquinte** [EIDA/userfeedback#11]
On behalf of Jerome Touvier.
A new account at B2ACCESS was created and a token was requested and stored in the default location (~/.eidatoken). Token attributes are:

> {"valid_until": "2019-05-30T07:35:08.917266Z", "cn": "TOUVIER J\u00e9r\u00f4me", "memberof": "/epos;/", "sn": "J\u00e9r\u00f4me", "issued": "2019-04-30T07:35:08.917272Z", "mail": "jerome.touvier@univ-grenoble-alpes.fr", "givenName": "TOUVIER", "expiration": "1m"}

The example with Obspy from the README file in this repository was used to download Z3 restricted data.

The error is:

```python
> from obspy.clients.fdsn import RoutingClient
> from obspy import UTCDateTime
> rsClient = RoutingClient("eida-routing", credentials={'EIDA_TOKEN': '/home/touvierj/.eidatoken'})
> st = rsClient.get_waveforms(network="Z3", channel="HHZ", starttime=UTCDateTime(2016, 3, 1), endtime=UTCDateTime(2016, 3, 1, 0, 2, 0))
/usr/local/lib/python3.7/dist-packages/obspy/clients/fdsn/routing/routing_client.py:99: UserWarning: Failed to download data of type 'station' from 'http://ws.resif.fr' due to:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/obspy/clients/fdsn/routing/routing_client.py", line 94, in _try_download_bulk
    return _download_bulk(r)
  File "/usr/local/lib/python3.7/dist-packages/obspy/clients/fdsn/routing/routing_client.py", line 122, in _download_bulk
    c.set_eida_token(r["credentials"]["EIDA_TOKEN"])
  File "/usr/local/lib/python3.7/dist-packages/obspy/clients/fdsn/client.py", line 312, in set_eida_token
    user, password = self._resolve_eida_token(token)
  File "/usr/local/lib/python3.7/dist-packages/obspy/clients/fdsn/client.py", line 376, in _resolve_eida_token
    user, password = response.decode().split(':')
ValueError: not enough values to unpack (expected 2, got 1)
  r["data_type"], r["endpoint"], reason))
```

**Comment by javiquinte** [comment]
The problem was that the user had not contacted the Network PI to get permissions to access the data. After being granted permission the problem was solved.
