### ISSUE TITLE
[Metadata] Stations in the VI network (SIL, Iceland) marked with lowercase letters.

### ISSUE THREAD

**Issue by web-sys1** [EIDA/userfeedback#157]
Please provide the following information in the content of the issue:
* Type of client used (Obspy, fdsnws_fetch, arclink_fetch): FDSNWS [Obspy]

Hello @jschaeff @javiquinte and @jbienkowski

It seems that the [VI network](https://www.orfeus-eu.org/fdsnws/station/1/query?network=VI&nodata=404) has issues that need to be addressed: it appears that the station codes of the VI network should start with capital letters. However, instead of uppercase, they are lowercase. These are: `VI-ada`, `Vi-fag`, `VI-asb`, `VI-gil`, `VI-god`, `VI-skr`

* screenshot or copy/paste of the error
* when was this exactly done?
* What is exactly wrong with the metadata?

``` xml
   <FDSNStationXML xmlns="http://www.fdsn.org/xml/station/1" schemaVersion="1.1">
         <Source>SeisComP</Source>
         <Sender>ODC</Sender>
         <Created>2024-01-04T19:33:51.868815</Created>
         <Network code="VI" startDate="1989-08-15T00:00:00" restrictedStatus="open">
               <Description>SIL  Icelandic national seismic network</Description>
               <Station code="ISKR" startDate="1996-10-01T00:00:00" restrictedStatus="open">
                     <Latitude>64.559998</Latitude>
                     <Longitude>-18.385999</Longitude>
                     <Elevation>858</Elevation>
                     <Site>
                           <Name>SKROKKALDA, ICELAND</Name>
                           <Country>ICELAND</Country>
                     </Site>
                     <CreationDate>1996-10-01T00:00:00</CreationDate>
               </Station>
               <Station code="asb" startDate="1994-08-01T00:00:00" restrictedStatus="open">
                     <Latitude>64.74818</Latitude>
                     <Longitude>-21.32535</Longitude>
                     <Elevation>94</Elevation>
                     <Site>
                           <Name>VI-asb</Name>
                     </Site>
                     <CreationDate>1994-08-01T00:00:00</CreationDate>
               </Station>
               <Station code="gil" startDate="1993-10-23T00:00:00" restrictedStatus="open">
                     <Latitude>66.07734</Latitude>
                     <Longitude>-16.35131</Longitude>
                     <Elevation>134</Elevation>
                     <Site>
                           <Name>VI-gil</Name>
                     </Site>
                     <CreationDate>1993-10-23T00:00:00</CreationDate>
               </Station>
               <Station code="god" startDate="2006-09-06T00:00:00" restrictedStatus="open">
                     <Latitude>63.65976</Latitude>
                     <Longitude>-19.32236</Longitude>
                     <Elevation>1200</Elevation>
                     <Site>
                           <Name>VI-god</Name>
                     </Site>
                     <CreationDate>2006-09-06T00:00:00</CreationDate>
               </Station>
               <Station code="skr" startDate="1996-10-02T00:00:00" restrictedStatus="open">
                     <Latitude>64.56014</Latitude>
                     <Longitude>-18.38647</Longitude>
                     <Elevation>858</Elevation>
                     <Site>
                           <Name>VI-skr</Name>
                     </Site>
                     <CreationDate>1996-10-02T00:00:00</CreationDate>
               </Station>
               <Station code="ada" startDate="1998-09-19T00:00:00" restrictedStatus="open">
                     <Latitude>65.01879</Latitude>
                     <Longitude>-15.57452</Longitude>
                     <Elevation>443</Elevation>
                     <Site>
                           <Name>VI-ada</Name>
                     </Site>
                     <CreationDate>1998-09-19T00:00:00</CreationDate>
               </Station>
               <Station code="fag" startDate="1999-05-14T00:00:00" restrictedStatus="open">
                     <Latitude>63.87478</Latitude>
                     <Longitude>-16.65364</Longitude>
                     <Elevation>27</Elevation>
                     <Site>
                           <Name>IMO</Name>
                           <Country>Iceland</Country>
                     </Site>
                     <CreationDate>1999-05-14T00:00:00</CreationDate>
               </Station>
         </Network>
   </FDSNStationXML>
```

**Comment by web-sys1** [comment]
```
Installed new opener with handlers: [<obspy.clients.fdsn.client.CustomRedirectHandler object at 0x000002D5E13B1090>]
Base URL: http://www.orfeus-eu.org
Request Headers: {'User-Agent': 'ObsPy/1.4.0 (Windows-10-10.0.19045-SP0, Python 3.10.13)'}
Loading discovered services from cache.
Downloading http://www.orfeus-eu.org/fdsnws/dataselect/1/query?starttime=2024-01-04T14%3A59%3A00.000000&endtime=2024-01-04T16%3A00%3A00.000000&network=VI&station=skr&location=--&channel=HHZ without requesting gzip compression
Downloaded http://www.orfeus-eu.org/fdsnws/dataselect/1/query?starttime=2024-01-04T14%3A59%3A00.000000&endtime=2024-01-04T16%3A00%3A00.000000&network=VI&station=skr&location=--&channel=HHZ with HTTP code: 204
[2024-01-04 21:53:10,386] ERROR in app: Exception on /api/seisPlot/ORFEUS/2024-01-04/VI.skr..HHZ_plot_H15.png [GET]
Traceback (most recent call last):
  File "D:\anaconda3\..\lib\site-packages\flask\app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\anaconda3\..\lib\site-packages\flask\app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\anaconda3\..\lib\site-packages\flask\app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\anaconda3\envs\..\lib\site-packages\flask\app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\HPKF04\Desktop\..\ms_app.py", line 125, in seisPlot
    fig, tr, *kargs = seisPlotter(
  File "c:\users\hpkf04\documents\github\seismicsonify\sonify\plotter.py", line 152, in seisPlotter
    st = client.get_waveforms(
  File "D:\anaconda3\envs\sonify\lib\site-packages\obspy\clients\fdsn\client.py", line 872, in get_waveforms
    data_stream = self._download(url, use_gzip=False)
  File "D:\anaconda3\envs\sonify\lib\site-packages\obspy\clients\fdsn\client.py", line 1486, in _download
    raise_on_error(code, data)
  File "D:\anaconda3\envs\sonify\lib\site-packages\obspy\clients\fdsn\client.py", line 1813, in raise_on_error
    raise FDSNNoDataException("No data available for request.",
obspy.clients.fdsn.header.FDSNNoDataException: No data available for request.
HTTP Status code: 204
Detailed response of server:

```

**Comment by web-sys1** [comment]
```
Installed new opener with handlers: [<obspy.clients.fdsn.client.CustomRedirectHandler object at 0x000001C7715733D0>]
Base URL: http://www.orfeus-eu.org
Request Headers: {'User-Agent': 'ObsPy/1.4.0 (Windows-10-10.0.19045-SP0, Python 3.11.3)'}
Downloading http://www.orfeus-eu.org/fdsnws/dataselect/1/application.wadl with requesting gzip compression
Downloading http://www.orfeus-eu.org/fdsnws/event/1/application.wadl with requesting gzip compression
Downloading http://www.orfeus-eu.org/fdsnws/station/1/application.wadl with requesting gzip compression
Downloading http://www.orfeus-eu.org/fdsnws/event/1/catalogs with requesting gzip compression
Downloading http://www.orfeus-eu.org/fdsnws/event/1/contributors with requesting gzip compression
Downloaded http://www.orfeus-eu.org/fdsnws/event/1/application.wadl with HTTP code: 200
Downloaded http://www.orfeus-eu.org/fdsnws/event/1/contributors with HTTP code: 200
Downloaded http://www.orfeus-eu.org/fdsnws/station/1/application.wadl with HTTP code: 200
Downloaded http://www.orfeus-eu.org/fdsnws/dataselect/1/application.wadl with HTTP code: 200
Downloaded http://www.orfeus-eu.org/fdsnws/event/1/catalogs with HTTP code: 200
Discovered event service
Discovered station service
Discovered dataselect service
Storing discovered services in cache.
Downloading http://www.orfeus-eu.org/fdsnws/dataselect/1/query?starttime=2023-12-13T00%3A00%3A01.000000&endtime=2023-12-14T00%3A00%3A00.000000&network=VI&station=skr&location=%2A&channel=HHZ without requesting gzip compression
Downloaded http://www.orfeus-eu.org/fdsnws/dataselect/1/query?starttime=2023-12-13T00%3A00%3A01.000000&endtime=2023-12-14T00%3A00%3A00.000000&network=VI&station=skr&location=%2A&channel=HHZ with HTTP code: 204
Traceback (most recent call last):
  File "C:\Users\HPKF04\Desktop\plot.py", line 84, in <module>
    raise error
  File "C:\Users\HPKF04\Desktop\plot.py", line 27, in <module>
    st = client.get_waveforms(net_argv, sta_argv, '*', cha_argv, start.replace(minute=0, second=1), endtime)
  File "D:\anaconda3\Lib\site-packages\obspy\clients\fdsn\client.py", line 872, in get_waveforms
    data_stream = self._download(url, use_gzip=False)
  File "D:\anaconda3\Lib\site-packages\obspy\clients\fdsn\client.py", line 1486, in _download
    raise_on_error(code, data)
  File "D:\anaconda3\Lib\site-packages\obspy\clients\fdsn\client.py", line 1813, in raise_on_error
    raise FDSNNoDataException("No data available for request.",
obspy.clients.fdsn.header.FDSNNoDataException: No data available for request.
HTTP Status code: 204
Detailed response of server:
```

**Comment by jfclinton** [comment]
Can the anonymous person writing under web-sys1 please indicate who they are?

John Clinton

**Comment by web-sys1** [comment]
> Can the anonymous person writing under web-sys1 please indicate who they are?
> 
> John Clinton

It doesn't matter who I am, It matters if I can reach you by mail.
