### ISSUE TITLE
[WFCatalog] currently not accessible on ETH node?

### ISSUE THREAD

**Issue by flofux** [EIDA/userfeedback#39]
Hi all,

it looks like WFCatalog Service is currently not working on ETH node:

Input:
`http://eida.ethz.ch/eidaws/wfcatalog/1/query`

Output:
Error 500: Internal Server Error
The connection to the database could not be established
Usage details are available from ENTER_URI_HERE
Request:
/wfcatalog/alpha/query
Request Submitted:
Tue Dec 03 2019 14:01:41 GMT+0000 (UTC)
Service Version:
1.0.0

**Comment by javiquinte** [comment]
Thanks for the feedback!
@sheimers Should the DB be restarted? Or the service?

**Comment by sheimers** [comment]
There are errors on the console where the service is running, the mongodb server is running. I will try to restart the service.

RangeError: Maximum call stack size exceeded
    at Date.toJSON (<anonymous>)
    at JSON.stringify (<anonymous>)
    at writeStream (/home/sysop/eidaqc/wfcatalog/service/server.js:825:21)
    at processDailyStream (/home/sysop/eidaqc/wfcatalog/service/server.js:725:12)
    at handleCallback (/home/sysop/eidaqc/wfcatalog/service/node_modules/mongodb/lib/utils.js:96:12)
    at /home/sysop/eidaqc/wfcatalog/service/node_modules/mongodb/lib/cursor.js:661:5
    at handleCallback (/home/sysop/eidaqc/wfcatalog/service/node_modules/mongodb-core/lib/cursor.js:159:5)
    at nextFunction (/home/sysop/eidaqc/wfcatalog/service/node_modules/mongodb-core/lib/cursor.js:683:5)
    at Cursor.next [as _next] (/home/sysop/eidaqc/wfcatalog/service/node_modules/mongodb-core/lib/cursor.js:693:3)
    at nextObject (/home/sysop/eidaqc/wfcatalog/service/node_modules/mongodb/lib/cursor.js:658:8)
[Worker 27656] killed with code: 1, and signal: null. Respawning.
[Worker 6] WFCatalog has been started on sqlx.ethz.ch:3000

/home/sysop/eidaqc/wfcatalog/service/node_modules/mongodb/lib/utils.js:98
    process.nextTick(function() { throw err; });
                                  ^

RangeError: Maximum call stack size exceeded
    at JSON.stringify (<anonymous>)
    at writeStream (/home/sysop/eidaqc/wfcatalog/service/server.js:825:21)
    at processDailyStream (/home/sysop/eidaqc/wfcatalog/service/server.js:725:12)
    at handleCallback (/home/sysop/eidaqc/wfcatalog/service/node_modules/mongodb/lib/utils.js:96:12)
    at /home/sysop/eidaqc/wfcatalog/service/node_modules/mongodb/lib/cursor.js:661:5
    at handleCallback (/home/sysop/eidaqc/wfcatalog/service/node_modules/mongodb-core/lib/cursor.js:159:5)
    at nextFunction (/home/sysop/eidaqc/wfcatalog/service/node_modules/mongodb-core/lib/cursor.js:683:5)
    at Cursor.next [as _next] (/home/sysop/eidaqc/wfcatalog/service/node_modules/mongodb-core/lib/cursor.js:693:3)
    at nextObject (/home/sysop/eidaqc/wfcatalog/service/node_modules/mongodb/lib/cursor.js:658:8)
    at Cursor.next (/home/sysop/eidaqc/wfcatalog/service/node_modules/mongodb/lib/cursor.js:262:12)
[Worker 17316] killed with code: 1, and signal: null. Respawning.
[W

**Comment by sheimers** [comment]
I have restarted mongodb and the WFcatalog service, it is up again. But sometimes I still get the error message from above when there is a request. Maybe it's because the mongodb server is under heavy load, we run several WFcatalog collector processes to reprocess old data that got lost some months ago due to a hardware failure.
The system load of mongod was very low until recently (even while processing the old data) and now jumped up to a constant 200%.

**Comment by jschaeff** [comment]
Hi @sheimers , just a wild guess, did you check that the indices are set in mongodb ? We lost them during a migration operation, and the mongodb server got slow and loaded.
Or maybe also it could be a good idea to remove the indices during your collection phase and rebuild them afterwards :

https://dev.knmi.nl/projects/eida/wiki/WFCatalog#Recommended-Database-Indices

**Comment by sheimers** [comment]
Yes, we have the following indices. 

db.daily_streams.stats()
...
  "indexSizes" : {
                "_id_" : 116559872,
                "fileId_1" : 86020096,
                "ts_1_net_1_sta_1" : 55668736,
                "files.name_1" : 110653440,
                "streamId_1" : 27947008
        },

**Comment by sheimers** [comment]
Now I notice I created the {streamId: 1} index on the wrong collection, daily_streams in stead of c_segments. I'll add it to c_segments now.

**Comment by sheimers** [comment]
Performance has improved now with the index added to c_segments, the load on the db server is down and processing with the collector got faster. thanks @jschaeff.  But I still get the error messages from the service.

**Comment by Jollyfant** [comment]
Hi, possibly the JSON that is being returned is too large. It could be a document with a huge number of continuous segments. I'm just guessing but you could try changing the limit from 0 (no limit) to something like 1000.

https://github.com/EIDA/wfcatalog/blob/a5d4ce5fc125862b591d09ccd9c9730012eb729c/service/server.js#L744

**Comment by sheimers** [comment]
@Jollyfant you are right, it depends on the size of the request. If I take a small network it works fine. If I select a single station of the large CH network it is also fine. But if I request only two days of the whole CH network it fails.
Is it expected behaviour to fail at only two days of data?

**Comment by Jollyfant** [comment]
No definitely not.. but maybe if your daily file has many, many continuous segments it may fail. We have some daily failes with > 200.000 traces so yeah.
