### ISSUE TITLE
[Federator] Internal error with a query to StationWS

### ISSUE THREAD

**Issue by javiquinte** [EIDA/userfeedback#76]
While querying the following URL an Internal Server Error is returned.

http://eida-federator.ethz.ch/fdsnws/station/1/query?minlat=44.09&maxlat=57.13&minlon=2.9&maxlon=13.04&format=text

```
Error 500: Internal server error

Internal server error

Usage details are available from http://www.fdsn.org/webservices/

Request:
http://eida-federator.ethz.ch/eidaws/station/text/1/query?minlat=44.09&maxlat=57.13&minlon=2.9&maxlon=13.04&format=text&minlat=44.09&maxlat=57.13&minlon=2.9&maxlon=13.04&format=text

Request Submitted:
2020-09-21T09:55:14.449276

Service version:
0.11.6
```

It was tried from browser and from console with the same result. One of the queries was at 2020-09-21 11:56:18.

**Comment by damb** [comment]
This for the catch. I'm going to fix it.

Thanks, @javiquinte.

**Comment by damb** [comment]
For completeness, the corresponding logs:

```
Sep 21 10:07:57 d6efedd7fc30 <EIDA> 2020-09-21T10:07:57+0000 CRITICAL eidaws.federator.middleware 51 middleware.py:66 - [544133ac-8750-4af1-973d-a4c2dd418c32] Local Exception: <class 'TypeError'>
Sep 21 10:07:57 d6efedd7fc30 <EIDA> 2020-09-21T10:07:57+0000 CRITICAL eidaws.federator.middleware 51 middleware.py:70 - [544133ac-8750-4af1-973d-a4c2dd418c32] Traceback information: ['Traceback (most recent call last):\n', '  File "/usr/local/src/eidaws/eidaws.federator/eidaws/federator/utils/middleware.py", line 46, in exception_handling_middleware\n    return await handler(request)\n', '  File "/usr/local/src/eidaws/eidaws.federator/eidaws/federator/utils/remote.py", line 16, in middleware\n    return await super().middleware(request, handler)\n', '  File "/var/www/eidaws-federator/venv/lib/python3.7/site-packages/aiohttp_remotes/x_forwarded.py", line 73, in middleware\n    return await handler(request)\n', '  File "/var/www/eidaws-federator/venv/lib/python3.7/site-packages/aiohttp/web_urldispatcher.py", line 892, in _iter\n    resp = await method()\n', '  File "/usr/local/src/eidaws/eidaws.federator/eidaws/federator/utils/view.py", line 52, in get\n    return await processor.federate(timeout=self.client_timeout)\n', '  File "/usr/local/src/eidaws/eidaws.federator/eidaws/federator/utils/process.py", line 104, in wrapper\n    return await coro(self, *args, **kwargs)\n', '  File "/usr/local/src/eidaws/eidaws.federator/eidaws/federator/utils/process.py", line 299, in federate\n    self._routed_urls, routes = await self._route()\n', '  File "/usr/local/src/eidaws/eidaws.federator/eidaws/federator/utils/process.py", line 254, in _route\n    async with req() as resp:\n', '  File "/var/www/eidaws-federator/venv/lib/python3.7/site-packages/aiohttp/client.py", line 1012, in __aenter__\n    self._resp = await self._coro\n', '  File "/var/www/eidaws-federator/venv/lib/python3.7/site-packages/aiohttp/client.py", line 473, in _request\n    ssl=ssl, proxy_headers=proxy_headers, traces=traces)\n', '  File "/var/www/eidaws-federator/venv/lib/python3.7/site-packages/aiohttp/client_reqrep.py", line 263, in __init__\n    url2 = url.with_query(params)\n', '  File "/var/www/eidaws-federator/venv/lib/python3.7/site-packages/yarl/_url.py", line 970, in with_query\n    new_query = self._get_str_query(*args, **kwargs)\n', '  File "/var/www/eidaws-federator/venv/lib/python3.7/site-packages/yarl/_url.py", line 931, in _get_str_query\n    query = "&".join(self._query_seq_pairs(quoter, query.items()))\n', '  File "/var/www/eidaws-federator/venv/lib/python3.7/site-packages/yarl/_url.py", line 901, in _query_seq_pairs\n    yield quoter(key) + "=" + quoter(cls._query_var(val))\n', '  File "/var/www/eidaws-federator/venv/lib/python3.7/site-packages/yarl/_url.py", line 912, in _query_var\n    "of type {}".format(v, type(v))\n', "TypeError: Invalid variable type: value should be str or int, got 44.09 of type <class 'float'>\n"]
```

**Comment by damb** [comment]
Fixed with https://github.com/damb/eidaws/commit/3c025ee711e0e270c804cf0af847bfe22bed9f6e.
