### ISSUE TITLE
All EIDA nodes should export seiscomp logs to file before end of year

### ISSUE THREAD

**Issue by jschaeff** [EIDA/userfeedback#78]
Following the email I sent lastly, It would be good to prepare data for the soon to come central stastic system in EIDA.

For this, all node should activate the export seiscomp logs to a logfile (Documentation to be provided by @andres-h 
Then, it is possible to run the aggregation script along with some log rotation, and it's only important to keep the aggregation result safe, the logfile can be deleted.

https://github.com/EIDA/eida-statistics explains how to run the aggregation script. I can help you out if necessary.

Please, each node report here when done or if any issue.

Thanks !

**Comment by jbienkowski** [comment]
ODC is already doing it.

**Comment by jbienkowski** [comment]
ODC is logging to files already (access + request).

**Comment by jan-michalek** [comment]
UIB: fdsnws.log

`HTTPAuthSessionWrapper.getChildWithDefault encountered unexpected error
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/twisted/web/_auth/wrapper.py", line 130, in render
    return self._authorizedResource(request).render(request)
  File "/usr/lib64/python2.7/site-packages/twisted/web/_auth/wrapper.py", line 121, in _authorizedResource
    return util.DeferredResource(self._login(credentials))
  File "/usr/lib64/python2.7/site-packages/twisted/web/_auth/wrapper.py", line 154, in _login
    d = self._portal.login(credentials, None, IResource)
  File "/usr/lib64/python2.7/site-packages/twisted/cred/portal.py", line 115, in login
    return maybeDeferred(self.checkers[i].requestAvatarId, credentials
--- <exception caught here> ---
  File "/usr/lib64/python2.7/site-packages/twisted/internet/defer.py", line 134, in maybeDeferred
    result = f(*args, **kw)
  File "/usr/lib64/python2.7/site-packages/twisted/cred/checkers.py", line 231, in requestAvatarId
    u, p = self.getUser(c.username)
  File "/usr/lib64/python2.7/site-packages/twisted/cred/checkers.py", line 219, in getUser
    self._cacheTimestamp = os.path.getmtime(self.filename)
  File "/usr/lib64/python2.7/genericpath.py", line 54, in getmtime
    return os.stat(filename).st_mtime
exceptions.OSError: [Errno 2] No such file or directory: '/home/sysop/.seiscomp/fdsnws.htpasswd'
`

**Comment by andres-h** [comment]
Did you turn off auth.enable? The option related to 
logging is trackdb.enable.

**Comment by jan-michalek** [comment]
> Did you turn off auth.enable? The option related to logging is trackdb.enable.
No, auth is still not in use at our node.

**Comment by jan-michalek** [comment]
I tried again but gettng only `fdsnws               is not running [WARNING]` but fdsnws.log is empty. Where to look for more log info?

**Comment by nikosT** [comment]
Hi Jan, it seems that the path to fdsnws.htpasswd is not valid

**Comment by andres-h** [comment]
On Fri, 29 Jan 2021 16:38:14 +0000 (UTC)
  Jan Michalek <notifications@github.com> wrote:
> I tried again but gettng only `fdsnws               is 
>not running [WARNING]` but fdsnws.log is empty. Where to 
>look for more log info?

That's weird, but you can stop fdsnws and try "seiscomp 
exec fdsnws --debug" to see messages on the console.

fdsnws.htpasswd is not needed in all configurations and in 
any case it should not depend on logging.

Andres
