### ISSUE TITLE
Problem with token at INGV

### ISSUE THREAD

**Issue by javiquinte** [EIDA/userfeedback#91]
On behalf of a user from KIT:

I am a PhD student at the Geophysical Institute at the KIT Karlsruhe and have been granted access to the AlpArray seismic data set (network code: Z3).
So far I have been downloading the data via the ObsPy FDSN Clients of the affiliated institutions with an EIDA-token I got from 'https://geofon.gfz-potsdam.de/eas/'.
This has worked fine for me until a few days ago the INGV Client stopped recognizing the EIDA-token.

Below you find a short summary of the problem:

```
from obspy.clients.fdsn import Client
cl = Client("INGV")
cl.set_eida_token('/home/bbraszus/Downloads/eidatoken',validate=True)

    Traceback (most recent call last):

          File "<ipython-input-131-e55e32d91049>", line 5, in <module>
            cl.set_eida_token('/home/bbraszus/Downloads/eidatoken',validate=True)
          File "/home/bbraszus/.local/lib/python3.8/site-packages/obspy/clients/fdsn/client.py", line 324, in set_eida_token
            user, password = self._resolve_eida_token(token, validate=validate)
          File "/home/bbraszus/.local/lib/python3.8/site-packages/obspy/clients/fdsn/client.py", line 356, in _resolve_eida_token
            raise FDSNException(msg)
        FDSNException: EIDA token authentication requested but service at 'http://webservices.ingv.it' does not specify /dataselect/auth in the dataselect/application.wadl.
```

The same syntax has worked before and still works for e.g. "cl = Client("LMU")". I already tried to download a new EIDA-token, even though the old was had not expired yet, but this did not solve the problem.

**Comment by massimo1962** [comment]
Hi @javiquinte , I try now with the following commandline:
```
wget --post-file token.asc http://webservices.ingv.it/fdsnws/dataselect/1/auth -O cred.txt
--2021-05-10 08:36:04--  http://webservices.ingv.it/fdsnws/dataselect/1/auth
Resolving webservices.ingv.it (webservices.ingv.it)... 93.63.207.206
Connecting to webservices.ingv.it (webservices.ingv.it)|93.63.207.206|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 41 [text/plain]
Saving to: ‘cred.txt’

cred.txt                                  100%[==================================================================================>]      41  --.-KB/s    in 0s      

2021-05-10 08:36:04 (2,16 MB/s) - ‘cred.txt’ saved [41/41]

```
consider that token.asc is the EAS token;

then

```
wget "http://`cat cred.txt`@webservices.ingv.it/fdsnws/dataselect/1/queryauth?starttime=2017-01-01T00:00:00Z&endtime=2017-01-01T12:00:00Z&network=Z3&station=A313A" -O data.mseed
--2021-05-10 08:36:11--  http://MKSW8PPIBa_AyVKZ2lI6NMZC:*password*@webservices.ingv.it/fdsnws/dataselect/1/queryauth?starttime=2017-01-01T00:00:00Z&endtime=2017-01-01T12:00:00Z&network=Z3&station=A313A
Resolving webservices.ingv.it (webservices.ingv.it)... 93.63.207.206
Connecting to webservices.ingv.it (webservices.ingv.it)|93.63.207.206|:80... connected.
HTTP request sent, awaiting response... 401 Unauthorized
Authentication selected: digest nonce="80b236fcc40068d9aa9abcfd", opaque="968e23f09f054ffa350690f5a4f7e064-ODBiMjM2ZmNjNDAwNjhkOWFhOWFiY2ZkLDkzLjYzLjIwNy4yMDYsMTYyMDYyODU3MQ==", qop="auth", algorithm="MD5", realm="authorization for restricted time series data required"
Reusing existing connection to webservices.ingv.it:80.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [application/vnd.fdsn.mseed]
Saving to: ‘data.mseed’

data.mseed 
``` 
and seem works correctly; today we can try with fdsnws_fetch...

**Comment by BeneBraszus** [comment]
Hi @massimo1962,
I originally reported the problem that Javier posted at the beginning of the issue. 
I usually use the ObsPy FDSN Client to retrieve seismic data. This currently works for all nodes except the "INGV" - as described above.
Using "wget" with your syntax I can also access the INGV data - the following works fine:
```
wget --post-file token.asc http://webservices.ingv.it/fdsnws/dataselect/1/auth -O cred.txt
wget "http://`cat cred.txt`@webservices.ingv.it/fdsnws/dataselect/1/queryauth?starttime=2017-01-01T00:00:00Z&endtime=2017-01-01T12:00:00Z&network=Z3&station=A313A" -O data.mseed
```

When using "fdsnws_fetch.py" (https://raw.githubusercontent.com/GEOFON/fdsnws_scripts/master/fdsnwsscripts/fdsnws_fetch.py) there are some other nodes where I do not get data from:
- LMU works fine
`python fdsnws_fetch.py -N 'Z3' -S 'A027A' -L '*' -C '*' -s "2017-01-01T07:00:00Z" -e "2017-01-01T07:05:00Z" -a 'eidatoken' -v -o data.mseed`
- INGV : "auth is not supported"
```
python fdsnws_fetch.py -N 'Z3' -S 'A31*A' -L '*' -C '*' -s "2017-01-01T07:00:00Z" -e "2017-01-01T07:05:00Z" -a 'eidatoken' -v -o data.mseed
using token in eidatoken:
{"valid_until": "2021-06-03T09:15:01.979991Z", "cn": "Benedikt Braszus", "memberof": "/epos;/epos/alparray;/", "sn": "Braszus", "issued": "2021-05-04T09:15:01.979996Z", "mail": "benedikt.braszus@kit.edu", "givenName": "Benedikt", "expiration": "1m"}

getting routes from http://geofon.gfz-potsdam.de/eidaws/routing/1/query?network=Z3&station=A31%2AA&location=%2A&channel=%2A&starttime=2017-01-01T07%3A00%3A00Z&endtime=2017-01-01T07%3A05%3A00Z&format=post
authentication at https://webservices.ingv.it/fdsnws/dataselect/1/auth is not supported
getting data from http://webservices.ingv.it/fdsnws/dataselect/1/query
getting data from http://webservices.ingv.it/fdsnws/dataselect/1/query failed with HTTP status code 403:
Error 403: Forbidden

access denied

Usage details are available from /fdsnws/dataselect/1/

Request:
/fdsnws/dataselect/1/query

Request Submitted:
2021-05-10T08:19:27.588092

Service Version:
1.1.0

did not receive data from Z3.A312A.*.*, Z3.A313A.*.*, Z3.A316A.*.*, Z3.A317A.*.*, Z3.A318A.*.*, Z3.A319A.*.*

```
- RESIF does not seem to work with "fdsnws_fetch.py" even though the RESIF ObsPy FDSN Client works for the exact same station and time ..
```
python fdsnws_fetch.py -N 'Z3' -S 'A156A' -L '*' -C '*' -s "2017-01-01T07:00:00Z" -e "2017-01-01T07:05:00Z" -a 'eidatoken' -v -o data.mseed
using token in eidatoken:
{"valid_until": "2021-06-03T09:15:01.979991Z", "cn": "Benedikt Braszus", "memberof": "/epos;/epos/alparray;/", "sn": "Braszus", "issued": "2021-05-04T09:15:01.979996Z", "mail": "benedikt.braszus@kit.edu", "givenName": "Benedikt", "expiration": "1m"}

getting routes from http://geofon.gfz-potsdam.de/eidaws/routing/1/query?network=Z3&station=A156A&location=%2A&channel=%2A&starttime=2017-01-01T07%3A00%3A00Z&endtime=2017-01-01T07%3A05%3A00Z&format=post
received no routes from http://geofon.gfz-potsdam.de/eidaws/routing/1/query?network=Z3&station=A156A&location=%2A&channel=%2A&starttime=2017-01-01T07%3A00%3A00Z&endtime=2017-01-01T07%3A05%3A00Z&format=post
did not receive routes to Z3.A156A.*.*

In case of problems with your request, plese use the contact form at

    http://www.orfeus-eu.org/organization/contact/form/?recipient=EIDA
```

Are these problems reproducable for you or is there an error somewhere on my side ? 

Cheers,
Benedikt

**Comment by massimo1962** [comment]
hi all,
thanks to @javiquinte 's explanation, now we have a right wadl. 
please @BeneBraszus could you check if your script works now?

**Comment by BeneBraszus** [comment]
Hi @massimo1962,
thanks for the answer. 
The fdsnws_fetch now works for the INGV, but still not for the RESIF stations.

Also the INGV ObsPy FDSN Client is still giving the same error when trying to load the EIDA-Token - this works fine for all other Clients:

```
from obspy.clients.fdsn import Client
cl = Client("INGV")
cl.set_eida_token('/home/bbraszus/Downloads/eidatoken',validate=True)
  
      Traceback (most recent call last):
      
        File "<ipython-input-164-eb1b618e0b4d>", line 3, in <module>
          cl.set_eida_token('/home/bbraszus/Downloads/eidatoken',validate=True)
      
        File "/home/bbraszus/.local/lib/python3.8/site-packages/obspy/clients/fdsn/client.py", line 324, in set_eida_token
          user, password = self._resolve_eida_token(token, validate=validate)
      
        File "/home/bbraszus/.local/lib/python3.8/site-packages/obspy/clients/fdsn/client.py", line 356, in _resolve_eida_token
          raise FDSNException(msg)
      
      FDSNException: EIDA token authentication requested but service at 'http://webservices.ingv.it' does not specify /dataselect/auth in the dataselect/application.wadl.
```
Cheers,
Benedikt
